# Server Port
server.port=8080

# Active Profile (Defaults to dev)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# JWT Configuration
application.security.jwt.secret-key=${JWT_SECRET_KEY:ThisIsADefaultSecretKeyThatIsAtLeast32BytesLongForDevEnvironment}
application.security.jwt.expiration=86400000

# File Upload configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Actuator Endpoints (Health Only)
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Spring Mail Defaults (non-secret parts)
spring.mail.host=${SPRING_MAIL_HOST:localhost}
spring.mail.port=${SPRING_MAIL_PORT:2525}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_AUTH:false}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_STARTTLS:false}
